# -*- mode:python; coding:utf-8; -*-

#  Calculation of π using quadrature using the Groovy programming language with some Java support.
#
#  Copyright © 2008–2013  Russel Winder

import os
import sys
sys.path.append('../site_scons')

from executablesupport import compileTargets, addCompileTarget, addRunTarget, createHelp

javaEnvironment = Environment(tools=['javac'])
javaEnvironment['ENV']['LANG'] = 'en_GB.UTF-8'

addCompileTarget(javaEnvironment.Java(target='.', source='ProcessSlice.java'))
addCompileTarget(javaEnvironment.Java(target='.', source='ProcessSlice_JCSP.java',
                                      JAVACLASSPATH=[os.environ['HOME'] + '/.m2/repository/org/codehaus/jcsp/jcsp/1.1-rc5/jcsp-1.1-rc5.jar']))

Default(compileTargets)

Help(createHelp())
