# -*- mode:python; coding:utf-8; -*-

#  Calculation of π using quadrature.
#
#  Copyright © 2008–2013  Russel Winder

import os
import sys
sys.path.append('../site_scons')

from executablesupport import compileTargets, addCompileTarget, addRunTarget, createHelp

#  As far as is known there is no occam implementation packaged in Debian Squeeze or Ubuntu Lucid.  We
#  therefore use KRoC which will be installed somewhere known to the shell.  It doesn't seem obvious how to
#  get a successful static link, so need to ensure LD_LIBRARY_PATH is correctly set to run the resulting
#  executable.

occamEnvironment = Environment(tools=[], ENV=os.environ)

for item in Glob('pi_*.occ'):
    root = os.path.splitext(item.name)[0]
    addRunTarget(occamEnvironment,
                 addCompileTarget(occamEnvironment.Command(root, item.name, 'kroc -o $TARGET $SOURCE')))

Default(compileTargets)

Help(createHelp())
