# -*- mode:python; coding:utf-8; -*-

#  Calculation of π using quadrature.
#
#  Copyright © 2008–2013  Russel Winder

import os
import sys
sys.path.append('../site_scons')

from executablesupport import compileTargets, addCompileTarget, addRunTarget, createHelp

clayEnvironment = Environment(tools=[], ENV=os.environ)

for item in Glob('pi_*.clay'):
    root = os.path.splitext(item.name)[0]
    addRunTarget(clayEnvironment,
                 addCompileTarget(clayEnvironment.Command(root, item.name, 'clay -o $TARGET $SOURCE')))

Default(compileTargets)

Help(createHelp())
