
Command('Sequential_Loop1', 'Sequential_Loop/main.pony', 'ponyc --pic Sequential_Loop')
Command('Sequential_Fold1', 'Sequential_Fold/main.pony', 'ponyc --pic Sequential_Fold')
Command('Parallel1', Glob('Parallel/*.pony'), 'ponyc --pic Parallel')

Alias('sequential', ['Sequential_Loop1', 'Sequential_Fold1'])
Alias('parallel', ['Parallel1'])
