# -*- mode:python; coding:utf-8; -*-

#  Calculation of π using quadrature.
#
#  Copyright © 2008–2013  Russel Winder

import os

cppBuildDirectory = 'Build_C++'
javaBuildDirectory = 'Build_Java'

packagePath = 'uk/org/winder/pi_quadrature'

cppGeneratedFilename = 'xxx_main_xxx.cc'

x10Environment = Environment(
    ENV=os.environ,
)

outputClass = 'src/{}/Output.x10'.format(packagePath)

for item in Glob('src/{}/Pi_*.x10'.format(packagePath)):
    x10ClassName = os.path.splitext(item.name)[0]
    #
    #  Java backend bits.
    #
    x10ClassFile = x10Environment.Command('{}/{}/{}.class'.format(javaBuildDirectory, packagePath, x10ClassName), [item, outputClass], 'x10c -d {} -O $SOURCES'.format(javaBuildDirectory))
    #
    # C++ backend bits.
    #
    x10Executable = x10Environment.Command(cppBuildDirectory + '/' + x10ClassName, [item, outputClass], 'x10c++ -O -d {0} -o {0}/{1} $SOURCES'.format(cppBuildDirectory, x10ClassName))

Clean('.', [cppBuildDirectory, javaBuildDirectory])
