# -*- mode: python; -*-

import os

environment = Environment(
    ENV=os.environ,
    RUST_HOME=os.environ['RUST_HOME'],
    BUILD_PATH='build'
)

Export('environment')

SConscript('SConscript', variant_dir=environment['BUILD_PATH'], duplicate=0)

Clean('.', environment['BUILD_PATH'])
