# -*- mode:python; coding:utf-8; -*-

#  Calculation of π using quadrature.
#
#  Copyright © 2013  Russel Winder

import os
import sys
sys.path.append('../site_scons')

from executablesupport import addCompileTarget, addRunTarget, createHelp, libraryPath

ceylonEnvironment = Environment(
    ENV = os.environ,
    JAVA_HOME=os.path.join(libraryPath(), 'JDK7')
    )

buildProducts = addCompileTarget(ceylonEnvironment.Command('compile', 'pi_sequential.ceylon', 'ceylon compile --src . $SOURCE'))

addRunTarget(ceylonEnvironment, buildProducts, 'ceylon run --run main default')

Default(buildProducts)

Clean(buildProducts, 'modules')

Help(createHelp())
