# -*- mode:python; coding:utf-8; -*-

#  Some languages do not have platform independent timing APIs, in particular, C, C++, and Erlang.  Code in
#  this directory relates to providing appropriate facilities.
#
#  Copyright © 2008, 2012, 2013  Russel Winder

environment = Environment(tools=['gcc', 'g++', 'gnulink'])

standAloneTests = [
    environment.Program(['microsecondTime_test.cpp', 'microsecondTime.c']),
    environment.Program(['rdtsc_test.c', 'rdtsc.c' ]),
    environment.Program(['processorSpeed_test.cpp', 'processorSpeed.cpp']),
]

Command('runTests', standAloneTests, ['./' + str(x[0]) for x in standAloneTests])
