# -*- mode:python; coding:utf-8; -*-

#  Calculation of π using quadrature using the D programming language.
#
#  Copyright © 2008–2015 Russel Winder

import os
import sys
sys.path.append('../site_scons')

from executablesupport import compileTargets, addCompileTarget, addRunTarget, createHelp

dEnvironment = {
    'dmd': Environment(
        tools=['dmd', 'link'],
        DFLAGS=['-O', '-release'],
    ),
    'gdc':  Environment(
        tools=['gdc', 'link'],
        DFLAGS=['-O3'],
    ),
    'ldc': Environment(
        # Potentially two ldc2 installed, one in the standard place another in the personal path. Need the environment
        # for the latter and also to know where the libraries are and add them to the LD_LIBRARY_PATH.
        ENV=os.environ,
        tools=['ldc', 'link'],
        DFLAGS=['-O', '-release'],
    ),
#}['dmd']
#}['gdc']
}['ldc']

dEnvironment['ENV']['LD_LIBRARY_PATH'] =  dEnvironment['ENV']['HOME'] + '/Built/lib'

outputFunctions = dEnvironment.Object('outputFunctions.d')

for item in Glob('pi_*.d'):
    root = os.path.splitext(item.name)[0]
    addRunTarget(dEnvironment, addCompileTarget(dEnvironment.Program([item, outputFunctions])))

Default(compileTargets)

Help(createHelp())
