# -*- mode:python; coding:utf-8; -*-

#  Calculation of π using quadrature.
#
#  Copyright © 2008–2013 Russel Winder

import os
import sys
sys.path.append('../site_scons')

from executablesupport import addRunTarget, createHelp

clojureEnvironment = Environment(tools=['javac'])

for item in Glob('pi_*.clj'):
    addRunTarget(clojureEnvironment, item, 'clojure -cp . {}')

    #Depends('run_pi_clojure_processSlice', processSliceClasses)

Help(createHelp())
