# -*- mode:python; coding:utf-8; -*-

#  Calculation of Pi using quadrature.
#
#  Copyright © 2008–2013 Russel Winder

import os
import sys
sys.path.append('../site_scons')

from executablesupport import compileTargets, addCompileTarget, runTargets, addRunTarget, executables, createHelp

clojureEnvironment = Environment(tools=['javac'])

for item in Glob('pi_*.clj'):
    addRunTarget(clojureEnvironment.Command('run_' + os.path.splitext(item.name)[0], item.name, 'clojure -cp . $SOURCE'))

    #Depends('run_pi_clojure_processSlice', processSliceClasses)

Help(createHelp())
