# -*- mode:python; coding:utf-8; -*-

#  Calculation of π using quadrature.
#
#  Copyright © 2008–2013 Russel Winder

import os
import sys
sys.path.append('../site_scons')

from executablesupport import compileTargets, addCompileTarget, addRunTarget, createHelp

clojureEnvironment = Environment(tools=[])

javaEnvironment = Environment(tools=['javac'])
javaEnvironment['ENV']['LANG'] = 'en_GB.UTF-8'

for item in Glob('pi_*.clj'):
    addRunTarget(clojureEnvironment, item, 'clojure -cp . {}')

Depends('run_pi_parallelMap_javaProcessSlice.clj',
        addCompileTarget(javaEnvironment.Java(target='.', source='../GroovyJava/ProcessSlice.java')))

Default(compileTargets)

Help(createHelp())
